sudo: false
os:
- linux
language: haskell
cache:
  directories:
  - "$HOME/.stack"
before_install:
- sudo add-apt-repository -y ppa:hvr/ghc
- sudo apt-get update
- sudo apt-get install cabal-install-3.0
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build --ghc-options='-Wall -Werror'
- stack haddock
script:
- "! grep -E -i '[?][?][?]|TODO' $(find src -iname '*.hs')"
- "! stack haddock --force-dirty 2>&1 | grep -P '^\\s*[0-9]{1,2}%'"
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
deploy:
- provider: script
  script: bash deploy.sh "$HACKAGE_USER" "$HACKAGE_PASSWORD"
  on:
    tags: true
- provider: pages
  local_dir: "$(stack path --local-doc-root)"
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    tags: true
env:
  global:
  - secure: pFjQ8ZAEU9jh7g7aEBgI2YBJW8BLwEl5nBPAr/3S3fYBvac2KdlEAsWeseJJpsv67JtHfcYwz2glw6MUuwuYFRGgo+3MoX3mF/Bvg1N0Y00o7jiGorihiP/MnYoIwlPtH7EuwDVb9XY87CKmDhPJbDqRUSTpfZBVZhidryt7XyQlgXVanmyeU9Q0Bpwklz+ER285JsYdr6PeH5UTZBUzZDpr7lYZ52z0jqJY+QBLqFN+FeEUIEDJsewu0Ti3fHCmOddtTDJdYsUcSRI+cpG6d2Jz6eYppW8cCvTh3tBFSf6i//F/UL/yLF+IyccAtXZmna4OIO3cdJU9JoPihnQluxsqQR1zGZSFOaQFquxM1N/FjzwQg+SYhBjZQBSsEK9qwkuG4gesBmKDiA+dAGsnn/TNkphbpl6ysPwhtViv4P/ikONZNhQZ+/U3JozChI/wIRyP6OsjHc7gE3v+vwqW7ybcHtDd3vHSxgQmQ92hrayWuPviEV4uvijc+hkOe9Wzp1BIWXxqb7M2zAxIJJVptvIMzbH7Fs+dY92+x0+cIwPGjT/CMFNhpPdpEVLy62UP91n3VgJ4VZHa7aiM1bppeqxSCndXAOvx/7ITqaq99qXkkHPjYIf4mQ2v0h/bG6T9kya1DekUgsMe1Bl5gRH6qWWHDezFC1cM8socUN9f8xk=
  - secure: ZMUpO36nnc4gsmon1kh4/xch85F5TxIfyiw2/95BCCcPL5/wQgmSKwMoqJ9HhT/G0+rmyIM1qTSC15flUPK5B2vf7n3BKnL2EGaoKRtC6G8IdNzhZ/TTcgj0U1inYLcoEGYWTIIHLaRLOn2uE1ZROLtqKLfsdHuymHsOD1XwFyOxFf91dk7FnsrnNyWa3YQQXncE30ZrUNFmRDCvFms2bPQ3CWo4JHJub0XsUFdLYeMJGGOMwJ7xVIJC/u1AqwZVREDccPOibpzVD/C3iaUCEsanZQzHZWZWzJfK7lW94xHeI/JDs1NG2EkZRR4Y5POImxtMuXSpe7IqG+tSe0g0XKX+saKbRVi/EOaFpqwSXBi3rJA37QcAU7VtpojX5GZbFqK1GyKPDu17vuT8TiFvdnb24pPh0gOlz0cQk3P6UNgHBT1UonO3KVxx3Y0j0GRNrZc2j4FZ/jWsOIjb4Rj77prrbotduzqR9to+ltfPBcZ6Xg3b79z/aeOkWnpvDlaxog6pLb5p3S1/M20WU0/xWtN3DpNIJGwwLWf0OOHb0ikY7Q/Bo6cGgFWi5Bj9LP3EYbXKB96kPN9SzMULSe29TUb9UPC5/EOzLzmBEWMbNxdcyKvOovY8TiUwGPwIemIG36+97F0ZhT0S+kcmabWn7NA/GsNjRt4sOL8a42/4iEI=
  - secure: RqCwRCJTE5TGc1s7B2zdoZDK0p7nQxthDR+9y2UTUMbFC80tqolMPjkyJLVJms+9ZGezjp12Eb7cZ4ORHzBdsm2VKlJ2hDUc1xqSenohTWURLh4uX7/wlGsDPnAkfyYgXk7rJO3EdJXw5DTQV9vXF2l3HsqLttUOLegcjDyXpFAuHRLQO4RHZQlPmbt5Cuyd2V5bk2xBVujlgnEgv7rMgozeFQGtpxFMFH4DBMtUCbXxMsdZfUx9uxqY0bLXSoD+ObRhEXUQtMwut0BvKe5jsvxdoo2PRq5Z72Mzkhg63Y4rKseM9XF9VeSvkpaQr7n3x01tfagzTOzBh8UVAysyj0Hbftm3n2QltQYoxRIer0sD7b82jTz9JPlvc1T7tD7w4APEvl4y67zmE47Gu5m+W1Z4tx3DsOdu2d5f6COezYIO+CVkq2mjAzb3FqJpK9Rpb/98CGmHoTSk2JLPg+xnCfY2IuBblfOLNLxQ0ENhGR0LjPKgDKpx6qZt0xAjWnqPifIc/OYLtABbmGPUfNA9yJCFa9krGjkagERUuUTfjtWuekS8bev5WuqQPCD+lbSnxAlMQgM9huN3I/dS1bC/9E1DTRT+eR8qSg4RWfZr+Kd167IRw7qcv1SZUmW60VE5Lxo/hbl68yjt6J0DdkIR2mXxm28d0uIdRZgNfEnXUek=
